# Generated by Django 4.2.7 on 2024-06-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_items_delete_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
