# Generated by Django 5.0.6 on 2024-06-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='customer',
        ),
        migrations.AddField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.user'),
        ),
    ]
