# Generated by Django 5.0.6 on 2024-06-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cart_product_alter_item_customer_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='cart_quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
