# Generated by Django 5.0.6 on 2024-06-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_quantity_cart_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='customer',
        ),
    ]
