# Generated by Django 5.0.6 on 2024-06-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_cart_quantity_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
