# Generated by Django 5.0.6 on 2024-07-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_item_cart_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
    ]
