# Generated by Django 5.0.6 on 2024-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_item_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
