# Generated by Django 5.0.6 on 2024-07-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='cart_item',
        ),
    ]
