# Generated by Django 5.0.6 on 2024-07-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_cart_cart_item_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_quantity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_quantity', to='shop.item'),
        ),
    ]
