# Generated by Django 5.0.6 on 2024-07-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_cart_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_quantity',
        ),
    ]
